[package]
name = "partial-lib-spec-solver"
version = "0.1.0"
authors = ["KangJing (Chaser) Huang <huang989@purdue.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clang = "0.23.0"